#! /usr/bin/env bash

set -euo pipefail

function install_ubuntu_18() {
    # for older versions

    apt_install_repo ppa:neovim-ppa/stable

    apt_update

    apt_install neovim

    echo_sub_task "Installing: Python Neovim packages"
    chronic pip install neovim
    chronic pip3 install neovim
}
