#! /usr/bin/env bash

set -euo pipefail

function install_ubuntu_18() {
    apt_install_all \
        build-essential \
        clang           \
        cmake           \
        gcc             \
        htop            \
        man             \
        python          \
        python-dev      \
        python-pip      \
        python3         \
        python3-dev     \
        python3-pip     \
        tree            \
        wget
}
